# Values are: NONE, AWS (for aws-ccm envs), or AWS-MANUAL (i.e., no aws-ccm):
CLOUD_PROVIDER                = NONE

# Disable wireguard only if your system cannot load the wireguard kernel module:
WIREGUARD_ENABLED             = false

# Currently supported: 3 or 1. Use the normal Rancher UI for registering additional nodes.
NODE_COUNT                    = 1
HELM_harbor_replicas          = 1
HELM_longhorn_replicas        = 1
HELM_cattle_replicas          = 1

# Used by all tooling to build MCM nodes.
SSH_USERNAME                  = {{ openspace_user }}

RKE2_API_VIP                  = {{ bundle.rke2_api_vip }}
RKE2_API_DNS                  = api.mcm.{{ domain_name }}

WILDCARD_INGRESS_VIP          = {{ bundle.wildcard_ingress_vip }}
WILDCARD_INGRESS_DNS          = mcm.{{ domain_name }}

VM_NIC_INTERFACE              = {{ bundle.nic_interface }}
CILIUM_DEVICE                 = {{ bundle.nic_interface }}