---
- name: Destroy requested OpenSpace VMs
  hosts: vms
  gather_facts: false
  serial: 1

  pre_tasks:
    # ============================================================
    # Load Bundle Configuration
    # ============================================================

    - name: Load bundle variables
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/../vars.yml"

    - name: Apply environment bundle overrides
      ansible.builtin.set_fact:
        bundle: >-
          {{
            bundle_vars |
            combine(
              bundle_overrides | default({}),
              recursive=true
            )
          }}

  vars:
    libvirt_host: "{{ groups['klm_host'][0] }}"

    vm_name: "{{ inventory_hostname }}"

    vm_disk_path: >-
      {{ bundle.libvirt.dirs.images }}/{{ inventory_hostname }}.qcow2

  tasks:

    # ============================================================
    # Check VM
    # ============================================================

    - name: Get list of existing VMs
      ansible.builtin.command:
        cmd: virsh list --all --name
      register: existing_vms
      changed_when: false
      delegate_to: "{{ libvirt_host }}"
      become: true

    - name: Determine if VM exists
      ansible.builtin.set_fact:
        vm_exists: "{{ vm_name in existing_vms.stdout_lines }}"


    # ============================================================
    # Stop VM
    # ============================================================

    - name: Get VM state
      ansible.builtin.command:
        cmd: "virsh domstate {{ vm_name }}"
      register: vm_state
      changed_when: false
      when: vm_exists
      delegate_to: "{{ libvirt_host }}"
      become: true

    - name: Force stop VM
      ansible.builtin.command:
        cmd: "virsh destroy {{ vm_name }}"
      when:
        - vm_exists
        - "'running' in vm_state.stdout"
      delegate_to: "{{ libvirt_host }}"
      become: true


    # ============================================================
    # Remove VM Definition
    # ============================================================

    - name: Undefine VM and remove NVRAM
      ansible.builtin.command:
        cmd: "virsh undefine {{ vm_name }} --nvram"
      when: vm_exists
      delegate_to: "{{ libvirt_host }}"
      become: true


    # ============================================================
    # Remove VM Disk
    # ============================================================

    - name: Check if VM disk exists
      ansible.builtin.stat:
        path: "{{ vm_disk_path }}"
      register: vm_disk
      delegate_to: "{{ libvirt_host }}"
      become: true

    - name: Remove VM qcow2 overlay
      ansible.builtin.file:
        path: "{{ vm_disk_path }}"
        state: absent
      when: vm_disk.stat.exists
      delegate_to: "{{ libvirt_host }}"
      become: true