version: '3'

tasks:
  full-install:
    desc: Complete Basekit Reference Architecture Install
    cmds:
      - task:
      - task:
      - task:

  node-prep:
    desc: Prepare nodes
    cmds:
      - task: klm:playbook
        vars:
          PLAYBOOK: node-prep.yml
          HOSTS: "{{.HOSTS}}"

