version: '3'

tasks:
  list:
    cmds:
      - task --list

  env:show:
    desc: Show selected KLM environment
    cmds:
      - |
          echo "KLM_HOME=$KLM_HOME"
          echo "KLM_ENV_NAME=$KLM_ENV_NAME"
          echo "KLM_ENV_DIR=$KLM_ENV_DIR"
          echo "KLM_BUNDLES_DIR=$KLM_BUNDLES_DIR"
          echo "KLM_DEPLOYMENT_FILE=$KLM_DEPLOYMENT_FILE"

  ansible-playbook:
    internal: true
    requires:
      vars: [PLAYBOOK]
    vars:
      LIMIT: '{{.LIMIT | default ""}}'
      EXTRA_VARS: '{{.EXTRA_VARS | default ""}}'
    cmds:
      - >
        ANSIBLE_CONFIG={{.ANSIBLE_CONFIG | default "/etc/klm/ansible.cfg"}}
        ansible-playbook
        -i {{.DEPLOYMENT_FILE}}
        {{.PLAYBOOK}}
        {{if .LIMIT}} --limit "{{.LIMIT}}" {{end}}
        {{if .EXTRA_VARS}} --extra-vars '{{.EXTRA_VARS}}' {{end}}