---
- name: Update OPNsense configuration
  hosts: klm_host
  gather_facts: false
  become: true

  vars:
    opnsense_config: /var/lib/libvirt/config/vm_config/opnsense/config.xml

  tasks:
    - name: Enable fargw in OPNsense config
      ansible.builtin.replace:
        path: "{{ opnsense_config }}"
        regexp: '<fargw>0</fargw>'
        replace: '<fargw>1</fargw>'