---
- name: Stage repository configuration
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Stage repository files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ klm_home }}/repos/{{ item | basename }}"
        mode: "0644"
      with_fileglob:
        - "{{ playbook_dir }}/../repos/*.repo"

    - name: Stage license files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ klm_home }}/license/openspace_license.json"
        mode: "0644"
      with_fileglob:
        - "{{ playbook_dir }}/../license/*"